/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_8;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author New Eng
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
      public AdminFrame() {
        initCostumComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initCostumComponents() {
        
        setTitle("Admin Dashboard");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(900, 600);
        setLocationRelativeTo(null);

        JPanel mainPanel = new JPanel();
        mainPanel.setBackground(new Color(245, 245, 245));
        mainPanel.setLayout(null);

        JLabel header = new JLabel("Admin Dashboard - Pending Courses");
        header.setFont(new Font("Segoe UI", Font.BOLD, 24));
        header.setBounds(20, 10, 500, 40);

        // TABLE — Pending Courses
        String[] columns = {"Course ID", "Title", "Instructor", "Status"};
        Object[][] data = {}; // will be filled using backend

        pendingTable = new JTable(data, columns);
        JScrollPane scroll = new JScrollPane(pendingTable);
        scroll.setBounds(20, 70, 500, 400);

        // DETAILS PANEL
        JPanel detailsPanel = new JPanel();
        detailsPanel.setLayout(null);
        detailsPanel.setBackground(Color.white);
        detailsPanel.setBorder(BorderFactory.createTitledBorder("Course Details"));
        detailsPanel.setBounds(540, 70, 330, 250);

        courseIdLabel = new JLabel("Course ID: ");
        titleLabel = new JLabel("Title: ");
        instructorLabel = new JLabel("Instructor: ");
        descLabel = new JLabel("<html>Description: <br></html>");

        courseIdLabel.setBounds(20, 30, 300, 25);
        titleLabel.setBounds(20, 60, 300, 25);
        instructorLabel.setBounds(20, 90, 300, 25);
        descLabel.setBounds(20, 120, 300, 100);

        detailsPanel.add(courseIdLabel);
        detailsPanel.add(titleLabel);
        detailsPanel.add(instructorLabel);
        detailsPanel.add(descLabel);

        // APPROVE / REJECT BUTTONS
        approveBtn = new JButton("Approve");
        rejectBtn = new JButton("Reject");

        approveBtn.setFont(new Font("Segoe UI", Font.BOLD, 16));
        rejectBtn.setFont(new Font("Segoe UI", Font.BOLD, 16));

        approveBtn.setBackground(new Color(0, 153, 76));
        approveBtn.setForeground(Color.white);

        rejectBtn.setBackground(new Color(204, 0, 0));
        rejectBtn.setForeground(Color.white);

        approveBtn.setBounds(550, 350, 140, 40);
        rejectBtn.setBounds(710, 350, 140, 40);

        // LISTENERS
        pendingTable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                fillDetails();
            }
        });

        approveBtn.addActionListener(e -> approveCourse());
        rejectBtn.addActionListener(e -> rejectCourse());

        mainPanel.add(header);
        mainPanel.add(scroll);
        mainPanel.add(detailsPanel);
        mainPanel.add(approveBtn);
        mainPanel.add(rejectBtn);

        add(mainPanel);
    }

    private void fillDetails() {
        int row = pendingTable.getSelectedRow();
        if (row == -1) return;

        String id = pendingTable.getValueAt(row, 0).toString();
        String title = pendingTable.getValueAt(row, 1).toString();
        String instructor = pendingTable.getValueAt(row, 2).toString();
        String desc = "Course description here"; // replace with backend fetch

        courseIdLabel.setText("Course ID: " + id);
        titleLabel.setText("Title: " + title);
        instructorLabel.setText("Instructor: " + instructor);
        descLabel.setText("<html>Description:<br>" + desc + "</html>");
    }

    private void approveCourse() {
        JOptionPane.showMessageDialog(this, "Course Approved (Backend Call Needed)");
        // call backend approveCourse()
    }

    private void rejectCourse() {
        JOptionPane.showMessageDialog(this, "Course Rejected (Backend Call Needed)");
        // call backend rejectCourse()
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
     
    private JTable pendingTable;
    private JButton approveBtn;
    private JButton rejectBtn;
    private JLabel courseIdLabel;
    private JLabel titleLabel;
    private JLabel instructorLabel;
    private JLabel descLabel;    
}
