/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_8;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author New Eng
 */
    public class Adminframe extends JFrame {
    private CourseManager courseManager;
    private JsonDatabaseManager db;
    private ArrayList<Course> pendingCourses;

    /**
     * Creates new form Adminframe
     */
     public Adminframe(CourseManager courseManager, JsonDatabaseManager db) {
        this.courseManager = courseManager;
        this.db = db;

        initUI();
        loadPendingCoursesTable();
    }
    //
    public Adminframe() {
        initUI();
    }  
    private void loadPendingCoursesTable() {

        if (courseManager == null) {
            return;  // avoid null pointer if using the empty constructor
        }

        pendingCourses = courseManager.getPendingCourses();

        String[] columns = {"Course ID", "Title", "Description", "Instructor ID"};

        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };

        for (Course c : pendingCourses) {
            model.addRow(new Object[]{
                c.getCourseId(),
                c.getTitle(),
                c.getDescription(),
                c.getInstructorId()
            });
        }

        courseTable.setModel(model);
    }

    private void approveCourse() {
        int row = courseTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a course to approve");
            return;
        }

        Course selected = pendingCourses.get(row);
        boolean ok = courseManager.approveCourse(selected.getCourseId());

        if (ok) {
            JOptionPane.showMessageDialog(this,
                    "Course \"" + selected.getTitle() + "\" approved!");
            loadPendingCoursesTable();
        }
    }

    private void rejectCourse() {
        int row = courseTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a course to reject");
            return;
        }

        Course selected = pendingCourses.get(row);
        boolean ok = courseManager.rejectCourse(selected.getCourseId());

        if (ok) {
            JOptionPane.showMessageDialog(this,
                    "Course \"" + selected.getTitle() + "\" rejected!");
            loadPendingCoursesTable();
        }
    }

    private void goBack() {
        this.dispose();
    }

    private void logout() {
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     

    private void initUI() {

        setTitle("Admin Dashboard");
        setSize(750, 480);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Toolbar
        toolbar = new JToolBar();
        toolbar.setFloatable(false);
        toolbarLabel = new JLabel("   Admin Dashboard");
        toolbar.add(toolbarLabel);

        // Table
        courseTable = new JTable();
        tableScroll = new JScrollPane(courseTable);

        // Buttons
        approveBtn = new JButton("Approve");
        rejectBtn = new JButton("Reject");
        backBtn = new JButton("Back");
        logoutBtn = new JButton("Logout");

        approveBtn.addActionListener(e -> approveCourse());
        rejectBtn.addActionListener(e -> rejectCourse());
        backBtn.addActionListener(e -> goBack());
        logoutBtn.addActionListener(e -> logout());

        // Layout
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableScroll, GroupLayout.PREFERRED_SIZE, 500, GroupLayout.PREFERRED_SIZE)
                .addGap(20)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(approveBtn, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                    .addComponent(rejectBtn, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbar, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25)
                        .addComponent(approveBtn)
                        .addGap(15)
                        .addComponent(rejectBtn)
                        .addGap(45)
                        .addComponent(backBtn)
                        .addGap(15)
                        .addComponent(logoutBtn))
                    .addComponent(tableScroll, GroupLayout.PREFERRED_SIZE, 380, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
    JsonDatabaseManager db = new JsonDatabaseManager();
    CourseManager cm = new CourseManager(db);
     new Adminframe(cm, db).setVisible(true);

   }  
    private JTable courseTable;
    private JScrollPane tableScroll;
    private JButton approveBtn;
    private JButton rejectBtn;
    private JButton backBtn;
    private JButton logoutBtn;
    private JToolBar toolbar;
    private JLabel toolbarLabel;
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

