/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_8;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author New Eng
 */
public class Adminframe extends JFrame {
    private CourseManager courseManager;
    private JsonDatabaseManager db;
    private ArrayList<Course> pendingCourses;

    /**
     * Creates new form Adminframe
     */
     public Adminframe(CourseManager courseManager, JsonDatabaseManager db) {
        this.courseManager = courseManager;
        this.db = db;

        initUI();
        loadPendingCoursesTable();
    }
    //
    // Empty constructor
    public Adminframe() {
        initUI();
    }
    private void loadPendingCoursesTable() {

        pendingCourses = courseManager.getPendingCourses();

        String[] columns = {"Course ID", "Title", "Description", "Instructor ID"};

        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };

        for (Course c : pendingCourses) {
            model.addRow(new Object[]{
                c.getCourseId(),
                c.getTitle(),
                c.getDescription(),
                c.getInstructorId()
            });
        }

        courseTable.setModel(model);
    }

    private void approveCourse() {
        int row = courseTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a course to approve");
            return;
        }

        Course selected = pendingCourses.get(row);
        boolean ok = courseManager.approveCourse(selected.getCourseId());

        if (ok) {
            JOptionPane.showMessageDialog(this,
                    "Course \"" + selected.getTitle() + "\" approved!");
            loadPendingCoursesTable();
        }
    }

    private void rejectCourse() {
        int row = courseTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a course to reject");
            return;
        }

        Course selected = pendingCourses.get(row);
        boolean ok = courseManager.rejectCourse(selected.getCourseId());

        if (ok) {
            JOptionPane.showMessageDialog(this,
                    "Course \"" + selected.getTitle() + "\" rejected!");
            loadPendingCoursesTable();
        }
    }

    private void goBack() {
        this.dispose();
    }

    private void logout() {
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void initUI() {

        // Toolbar
        toolbar = new JToolBar();
        toolbar.setFloatable(false);

        toolbarLabel = new JLabel("    Admin Dashboard");
        toolbar.add(toolbarLabel);

        // Table
        courseTable = new JTable();
        tableScroll = new JScrollPane(courseTable);

        // Buttons
        approveBtn = new JToggleButton("Approve");
        rejectBtn = new JToggleButton("Reject");
        backBtn = new JToggleButton("Back");
        logoutBtn = new JToggleButton("Logout");

        approveBtn.addActionListener(e -> approveCourse());
        rejectBtn.addActionListener(e -> rejectCourse());
        backBtn.addActionListener(e -> goBack());
        logoutBtn.addActionListener(e -> logout());

        // Layout
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(toolbar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tableScroll, GroupLayout.PREFERRED_SIZE, 380, GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(approveBtn, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
                        .addComponent(rejectBtn, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
                        .addComponent(backBtn, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
                        .addComponent(logoutBtn, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(12, Short.MAX_VALUE))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(toolbar, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(approveBtn)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rejectBtn)
                            .addGap(60, 60, 60)
                            .addComponent(backBtn)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(logoutBtn))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tableScroll, GroupLayout.PREFERRED_SIZE, 280, GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setTitle("Admin Dashboard");
        setLocationRelativeTo(null);
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminframe().setVisible(true);
            }
        });
    }
    private JTable courseTable;
    private JScrollPane tableScroll;
    private JToggleButton approveBtn;
    private JToggleButton rejectBtn;
    private JToggleButton backBtn;
    private JToggleButton logoutBtn;
    private JToolBar toolbar;
    private JLabel toolbarLabel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
