package lab_8;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gehad
 */

public class InstructorCoursesFrame extends javax.swing.JFrame {

   private JsonDatabaseManager dbManager;
private CourseManager courseManager;
private Instructor instructor;
private DefaultTableModel tableModel;

public InstructorCoursesFrame(Instructor instructor) {
initComponents();
this.instructor = instructor;
tableModel = (DefaultTableModel) CoursesTable.getModel();
dbManager = new JsonDatabaseManager();           // load JSON data
courseManager = new CourseManager(dbManager);    // connect CourseManager to DB
loadCourses();
}

public InstructorCoursesFrame() {
initComponents();
}

// Load only courses created by this instructor
private void loadCourses() {
tableModel.setRowCount(0); // clear existing rows

List<Course> myCourses = courseManager.getCoursesByInstructor(instructor.getUserId());

for (Course c : myCourses) {
    tableModel.addRow(new Object[]{
        c.getCourseId(),
        c.getTitle(),
        c.getDescription()
    });
}

addExtraRows(5);


}

// Add empty rows for spacing/input
private void addExtraRows(int extraRows) {
for (int i = 0; i < extraRows; i++) {
tableModel.addRow(new Object[]{"", "", ""});
}
}

// Refresh courses table (use after add/edit/delete)
public void refreshCourses() {
tableModel.setRowCount(0);
loadCourses();
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CoursesTable = new javax.swing.JTable();
        CreateButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("==Manage Your Courses==");

        CoursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course ID", "Title", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CoursesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CoursesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CoursesTable);

        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateButton)
                .addGap(30, 30, 30)
                .addComponent(UpdateButton)
                .addGap(29, 29, 29)
                .addComponent(DeleteButton)
                .addGap(30, 30, 30)
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateButton)
                    .addComponent(UpdateButton)
                    .addComponent(DeleteButton)
                    .addComponent(BackButton))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed

int rowCount = tableModel.getRowCount();
boolean added = false;

for (int row = 0; row < rowCount; row++) {
    String courseIdCell = (tableModel.getValueAt(row, 0) != null) ? tableModel.getValueAt(row, 0).toString() : "";
    String titleCell = (tableModel.getValueAt(row, 1) != null) ? tableModel.getValueAt(row, 1).toString().trim() : "";

    // Only create if the row has a title but no ID yet
    if (courseIdCell.isEmpty() && !titleCell.isEmpty()) {
        String description = (tableModel.getValueAt(row, 2) != null) ? tableModel.getValueAt(row, 2).toString() : "";

        // Create course via CourseManager
        Course newCourse = courseManager.addCourse(titleCell, description, instructor.getUserId());

        if (newCourse != null) {
            // Update instructor's created courses
            if (!instructor.getCreatedCourses().contains(newCourse.getCourseId())) {
                  instructor.addCourse(courseManager, titleCell, description) ;

            }

            // Update table with generated course ID
            tableModel.setValueAt(newCourse.getCourseId(), row, 0);

            // Save instructor changes to JSON

            dbManager.saveCourses();
            dbManager.saveUsers();

            added = true;
        }

        break; // only create one course per click
    }
}

if (added) {
    refreshCourses(); // reload table to show new course
    JOptionPane.showMessageDialog(this, "Course created successfully!");
} else {
    JOptionPane.showMessageDialog(this, "Please enter a course title to create a course.");
}

    }//GEN-LAST:event_CreateButtonActionPerformed

    private void CoursesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoursesTableMouseClicked
       int row = CoursesTable.getSelectedRow();
if (row >= 0) {
    // Get the table model directly from the JTable
    DefaultTableModel model = (DefaultTableModel) CoursesTable.getModel();

    // Retrieve values safely
    String courseId = model.getValueAt(row, 0).toString();
    String title = model.getValueAt(row, 1).toString();
    String desc = model.getValueAt(row, 2).toString();

    // Optionally, show details in text fields if you have them
    // txtCourseId.setText(courseId);
    // txtTitle.setText(title);
    // txtDescription.setText(desc);
}

    }//GEN-LAST:event_CoursesTableMouseClicked

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed

int rowCount = tableModel.getRowCount();
boolean edited = false;
for (int row = 0; row < rowCount; row++) {
    String courseIdCell = (tableModel.getValueAt(row, 0) != null) ? tableModel.getValueAt(row, 0).toString() : "";
    String titleCell = (tableModel.getValueAt(row, 1) != null) ? tableModel.getValueAt(row, 1).toString().trim() : "";
    String descriptionCell = (tableModel.getValueAt(row, 2) != null) ? tableModel.getValueAt(row, 2).toString() : "";

    if (!courseIdCell.isEmpty()) {
        Course c = courseManager.getCourse(courseIdCell);
        if (c != null && c.getInstructorId().equals(instructor.getUserId())) {
            if (!c.getTitle().equals(titleCell) || !c.getDescription().equals(descriptionCell)) {
                c.setTitle(titleCell);
                c.setDescription(descriptionCell);
                edited = true;
            }
        }
    }
}

if (edited) {
    dbManager.saveCourses();
    JOptionPane.showMessageDialog(this, "Courses updated successfully!");
    refreshCourses();
} else {
    JOptionPane.showMessageDialog(this, "No changes detected.");
}
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
      int selectedRow = CoursesTable.getSelectedRow();
if (selectedRow == -1) {
JOptionPane.showMessageDialog(this, "Please select a course to delete.");
return;
}
String courseId = (tableModel.getValueAt(selectedRow, 0) != null) ? tableModel.getValueAt(selectedRow, 0).toString() : "";
if (courseId.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Cannot delete an empty row.");
    return;
}

Course c = courseManager.getCourse(courseId);
if (c != null && c.getInstructorId().equals(instructor.getUserId())) {
    courseManager.deleteCourse(courseId); // removes from courses list and saves courses.json
    instructor.getCreatedCourses().remove(courseId);
    dbManager.saveUsers();       // save updated instructor list
    tableModel.removeRow(selectedRow);
    JOptionPane.showMessageDialog(this, "Course deleted successfully!");
} else {
    JOptionPane.showMessageDialog(this, "You do not have permission to delete this course.");
}
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // Close current frame
    this.dispose();
    // Open Instructor Dashboard
    InstructorDashboardFrame dashboard = new InstructorDashboardFrame(instructor);
    dashboard.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorCoursesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InstructorCoursesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTable CoursesTable;
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
