/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_8;

/**
 *
 * @author Gehad
 */

import javax.swing.*;
import java.util.List;
import java.util.stream.Collectors;

public class InstructorViewInsightsFrame extends javax.swing.JFrame {

private Instructor instructor;
private CourseManager courseManager;
private ChartFrame chartFrame;
private JsonDatabaseManager dbManager;

public InstructorViewInsightsFrame(Instructor instructor, CourseManager courseManager, JsonDatabaseManager dbManager) {
    this.instructor = instructor;
    this.courseManager = courseManager;
    this.dbManager = dbManager;
    initComponents(); // NetBeans GUI-generated components
    setupInsightsPanel();
}
public InstructorViewInsightsFrame() {
    initComponents(); 
}

private void setupInsightsPanel() {
    chartFrame = new ChartFrame("Course Analytics");

    // Populate courses combo box
    courseComboBox.removeAllItems();
    List<Course> instructorCourses = courseManager.getCoursesByInstructor(instructor.getUserId());
    for (Course c : instructorCourses) {
        courseComboBox.addItem(c.getTitle());
    }

    // Automatically select the first course and refresh charts
    if (courseComboBox.getItemCount() > 0) {
        courseComboBox.setSelectedIndex(0);
        refreshCharts();
    }

    // When course changes, refresh charts automatically
    courseComboBox.addActionListener(e -> refreshCharts());

    // Show Analytics button
    showAnalyticsButton.addActionListener(e -> {
        refreshCharts();
        if (!chartFrame.isVisible()) chartFrame.setVisible(true);
        chartFrame.toFront();
        chartFrame.repaint();
    });
}

private void refreshCharts() {
    String selectedCourseTitle = (String) courseComboBox.getSelectedItem();
    if (selectedCourseTitle == null) return;

    Course selectedCourse = getCourseByTitle(selectedCourseTitle);
    if (selectedCourse == null) return;

    // Get enrolled students
    List<String> enrolledStudentIds = instructor.viewEnrolledStudents(courseManager, selectedCourse.getCourseId());
    if (enrolledStudentIds == null) return;

    List<Student> students = enrolledStudentIds.stream()
            .map(id -> dbManager.getStudentById(id))
            .filter(s -> s != null)
            .collect(Collectors.toList());

    // Update charts (all lessons aggregated into course-level view)
    chartFrame.updateCharts(selectedCourse, students, instructor);
}

private Course getCourseByTitle(String title) {
    List<Course> instructorCourses = courseManager.getCoursesByInstructor(instructor.getUserId());
    for (Course c : instructorCourses) {
        if (c.getTitle().equals(title)) return c;
    }
    return null;
}








   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        courseComboBox = new javax.swing.JComboBox<>();
        BottomPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        showAnalyticsButton = new javax.swing.JButton();
        CenterPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TopPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("==Veiw Analytics==");

        jLabel2.setText("Select Course:");

        courseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 62, Short.MAX_VALUE))
        );

        TopPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(TopPanel, java.awt.BorderLayout.PAGE_START);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        BottomPanel.add(backButton);

        showAnalyticsButton.setText("Show analytics");
        showAnalyticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAnalyticsButtonActionPerformed(evt);
            }
        });
        BottomPanel.add(showAnalyticsButton);

        getContentPane().add(BottomPanel, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(CenterPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void showAnalyticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAnalyticsButtonActionPerformed

// Refresh the charts based on current selections
refreshCharts();

// Make sure the chart window is visible
if (!chartFrame.isVisible()) {
    chartFrame.setVisible(true);
}

// Bring chart window to front
chartFrame.toFront();
chartFrame.repaint();

   

    }//GEN-LAST:event_showAnalyticsButtonActionPerformed

    private void courseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboBoxActionPerformed
// Course Combo Box Action
// Get selected course title
String selectedCourseTitle = (String) courseComboBox.getSelectedItem();
if (selectedCourseTitle == null) return;

// Find the Course object
Course selectedCourse = getCourseByTitle(selectedCourseTitle);
if (selectedCourse == null) return;

// Refresh the charts for the selected course
refreshCharts();

    }//GEN-LAST:event_courseComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorViewInsightsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorViewInsightsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorViewInsightsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorViewInsightsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InstructorViewInsightsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton showAnalyticsButton;
    // End of variables declaration//GEN-END:variables
}
