/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_8;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Gehad
 */
public class InstructorAddQuestionsFrame extends javax.swing.JFrame {
private Instructor instructor;
private JsonDatabaseManager dbManager = new JsonDatabaseManager();
private CourseManager courseManager=new CourseManager(dbManager);
private LessonManager lessonManager; 
private String courseId;
private String lessonId;
private String quizTitle;
    
    public InstructorAddQuestionsFrame(Instructor instructor, CourseManager courseManager, 
                                   LessonManager lessonManager, String courseId, 
                                   String lessonId, String quizTitle) {
    this.instructor = instructor;
    this.courseManager = courseManager;
    this.lessonManager = lessonManager;
    this.courseId = courseId;
    this.lessonId = lessonId;
    this.quizTitle = quizTitle;
    
    initComponents(); 
}

    public InstructorAddQuestionsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Questiontxt = new javax.swing.JTextField();
        Choice1txt = new javax.swing.JTextField();
        Choice2txt = new javax.swing.JTextField();
        Choice3txt = new javax.swing.JTextField();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        AddButton = new javax.swing.JButton();
        finishQuizButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("==Add Questions to Quiz==");

        jLabel2.setText("Question:");

        jLabel3.setText("Choice 1:");

        jLabel4.setText("Choice 2:");

        jLabel5.setText("Choice 3:");

        Questiontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestiontxtActionPerformed(evt);
            }
        });

        Choice1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choice1txtActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio1);
        radio1.setText("correct");
        radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio2);
        radio2.setText("correct");

        buttonGroup1.add(radio3);
        radio3.setText("correct");

        AddButton.setText("Add Question");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        finishQuizButton.setText("Finish Quiz");
        finishQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishQuizButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Questiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(finishQuizButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Choice3txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                        .addComponent(Choice2txt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Choice1txt, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radio1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(radio2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(radio3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Questiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Choice1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Choice2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Choice3txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(finishQuizButton))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuestiontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestiontxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestiontxtActionPerformed

    private void Choice1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choice1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Choice1txtActionPerformed

    private void radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio1ActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
                                                  
    // Collect question data from text fields
    String questionText = Questiontxt.getText().trim();
    String choice1 = Choice1txt.getText().trim();
    String choice2 = Choice2txt.getText().trim();
    String choice3 = Choice3txt.getText().trim();

    // Determine which radio button is selected (correct answer)
    int correctIndex = -1;
    if (radio1.isSelected()) correctIndex = 0;
    else if (radio2.isSelected()) correctIndex = 1;
    else if (radio3.isSelected()) correctIndex = 2;

    if (questionText.isEmpty() || choice1.isEmpty() || choice2.isEmpty() || choice3.isEmpty() || correctIndex == -1) {
        JOptionPane.showMessageDialog(this, "Please fill all fields and select the correct answer.");
        return;
    }

    // Create the Question object
    List<String> options = new ArrayList<>();
    options.add(choice1);
    options.add(choice2);
    options.add(choice3);

    Question question = new Question(questionText, options, correctIndex);

    // Add question to the quiz
    boolean added = instructor.addQuestionToQuiz(courseManager, lessonManager, courseId, lessonId, quizTitle, question);
    if (added) {
        JOptionPane.showMessageDialog(this, "Question added!");
        // Clear fields for next question
        Questiontxt.setText("");
        Choice1txt.setText("");
        Choice2txt.setText("");
        Choice3txt.setText("");
        buttonGroup1.clearSelection();  // clear radio buttons

        // Enable Finish Quiz button if at least one question exists
        finishQuizButton.setEnabled(true);
    } else {
        JOptionPane.showMessageDialog(this, "Failed to add question.");
    }


    }//GEN-LAST:event_AddButtonActionPerformed

    private void finishQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishQuizButtonActionPerformed
    // 1. Get input from text fields
String questionText = Questiontxt.getText().trim();
String choice1 = Choice1txt.getText().trim();
String choice2 = Choice2txt.getText().trim();
String choice3 = Choice3txt.getText().trim();

// 2. Determine selected radio button
int correctIndex = -1;
if (radio1.isSelected()) correctIndex = 0;
else if (radio2.isSelected()) correctIndex = 1;
else if (radio3.isSelected()) correctIndex = 2;

// 3. Validate input
if (questionText.isEmpty() || choice1.isEmpty() || choice2.isEmpty() || choice3.isEmpty() || correctIndex == -1) {
    JOptionPane.showMessageDialog(this, "Please fill all fields and select the correct answer.");
    return;
}

// 4. Create Question object
List<String> options = new ArrayList<>();
options.add(choice1);
options.add(choice2);
options.add(choice3);
Question question = new Question(questionText, options, correctIndex);

// 5. Add question to quiz using the Instructor method
boolean added = instructor.addQuestionToQuiz(courseManager, lessonManager, courseId, lessonId, quizTitle, question);

// 6. Notify user
if (added) {
    JOptionPane.showMessageDialog(this, "Question added successfully!");
    Questiontxt.setText("");
    Choice1txt.setText("");
    Choice2txt.setText("");
    Choice3txt.setText("");
    buttonGroup1.clearSelection();

    finishQuizButton.setEnabled(true);
} else {
    JOptionPane.showMessageDialog(this, "Failed to add question.");
}

    }//GEN-LAST:event_finishQuizButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorAddQuestionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorAddQuestionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorAddQuestionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorAddQuestionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InstructorAddQuestionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField Choice1txt;
    private javax.swing.JTextField Choice2txt;
    private javax.swing.JTextField Choice3txt;
    private javax.swing.JTextField Questiontxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton finishQuizButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    // End of variables declaration//GEN-END:variables
}
