/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_8;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gehad
 */
public class InstructorCreateQuiz extends javax.swing.JFrame {
private Instructor instructor;
private JsonDatabaseManager dbManager = new JsonDatabaseManager();
private CourseManager courseManager=new CourseManager(dbManager);
private LessonManager lessonManager; 


public InstructorCreateQuiz(Instructor instructor, CourseManager courseManager,LessonManager lessonManager) {
    this.instructor = instructor;
    this.courseManager =courseManager;
    this.lessonManager = lessonManager;

    initComponents();  // NetBeans generated UI setup

    // Load courses immediately
    loadCourses();
    lessonComboBox.setEnabled(false);
    createQuizButton.setEnabled(false);

    // Automatically populate lessons when the first course is selected
    if (courseComboBox.getItemCount() > 0) {
        courseComboBox.setSelectedIndex(0);
        loadSelectedCourseLessons();
    }

    // Add create button action
    createQuizButton.addActionListener(e -> createQuizManually());
}

public InstructorCreateQuiz() {
    initComponents();  // NetBeans generated UI setup
}

// -------------------- Helper Methods --------------------

private void loadCourses() {
    courseComboBox.removeAllItems();
    for (Course c : courseManager.getCoursesByInstructor(instructor.getUserId())) {
        courseComboBox.addItem(c.getCourseId() + " - " + c.getTitle());
    }
}

private void loadSelectedCourseLessons() {
    lessonComboBox.removeAllItems();
    String courseId = getSelectedCourseId();
    if (courseId == null) return;

    Course course = courseManager.getCourse(courseId);
    if (course != null) {
        for (Lesson lesson : lessonManager.getAllLessons(course)) {
            lessonComboBox.addItem(lesson.getLessonId() + " - " + lesson.getTitle());
        }
        lessonComboBox.setEnabled(true);
    }
}

private String getSelectedCourseId() {
    String selected = (String) courseComboBox.getSelectedItem();
    if (selected == null) return null;
    return selected.split(" - ")[0];
}

private String getSelectedLessonId() {
    String selected = (String) lessonComboBox.getSelectedItem();
    if (selected == null) return null;
    return selected.split(" - ")[0];
}

private void createQuizManually() {
    String courseId = getSelectedCourseId();
    String lessonId = getSelectedLessonId();
    String quizTitle = quizTitleField.getText().trim();

    if (courseId == null || lessonId == null || quizTitle.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Select course, lesson, and enter quiz title.");
        return;
    }

    boolean created = instructor.addQuiz(lessonManager, courseManager,courseId, lessonId, quizTitle, 0, new java.util.ArrayList<>());

    if (created) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Quiz created! Now you can add questions.");
        // TODO: Open questions frame for adding questions
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Failed to create quiz. Check your selections.");
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        courseComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lessonComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        quizTitleField = new javax.swing.JTextField();
        createQuizButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("==Create Quiz==");

        jLabel2.setText("Select Course:");

        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        courseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Select Lesson:");

        lessonComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lessonComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessonComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Quiz Title:");

        quizTitleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizTitleFieldActionPerformed(evt);
            }
        });

        createQuizButton.setText("Create Quiz");
        createQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createQuizButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quizTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lessonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(createQuizButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lessonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(quizTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createQuizButton)
                .addGap(0, 102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createQuizButtonActionPerformed
        
    String courseId = getSelectedCourseId();
    String lessonId = getSelectedLessonId();
    String quizTitle = quizTitleField.getText().trim();

    if (courseId == null || lessonId == null || quizTitle.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a course, lesson, and enter a quiz title.");
        return;
    }

    boolean created = instructor.addQuiz(lessonManager,courseManager,courseId, lessonId, quizTitle, 0, new ArrayList<>());

    if (created) {
        JOptionPane.showMessageDialog(this, "Quiz created! Now you can add questions.");
        // TODO: Open InstructorAddQuestionsFrame here
    } else {
        JOptionPane.showMessageDialog(this, "Failed to create quiz. Check your selections.");
    }


    }//GEN-LAST:event_createQuizButtonActionPerformed

    private void courseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboBoxActionPerformed

    String selectedCourseId = getSelectedCourseId(); // helper method
    if (selectedCourseId == null) {
        lessonComboBox.setEnabled(false);
        createQuizButton.setEnabled(false);
        return;
    }

    lessonComboBox.removeAllItems();
    Course c = courseManager.getCourse(selectedCourseId);
    if (c != null) {
        for (Lesson l : lessonManager.getAllLessons(c)) {
            lessonComboBox.addItem(l.getLessonId() + " - " + l.getTitle());
        }
        lessonComboBox.setEnabled(true);
    }
    createQuizButton.setEnabled(false); // will enable when lesson selected & title entered
    }//GEN-LAST:event_courseComboBoxActionPerformed

    private void lessonComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessonComboBoxActionPerformed
  
    String lessonId = getSelectedLessonId(); // helper method
    String title = quizTitleField.getText().trim();
    createQuizButton.setEnabled(lessonId != null && !title.isEmpty());
    }//GEN-LAST:event_lessonComboBoxActionPerformed

    private void quizTitleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizTitleFieldActionPerformed
                                                    
    // Get the typed title
    String quizTitle = quizTitleField.getText().trim();

    // Check if a course and lesson are selected
    String courseId = getSelectedCourseId();
    String lessonId = getSelectedLessonId();

    // Enable the Create Quiz button only if all required fields have values
    if (courseId != null && lessonId != null && !quizTitle.isEmpty()) {
        createQuizButton.setEnabled(true);
    } else {
        createQuizButton.setEnabled(false);
    }

    }//GEN-LAST:event_quizTitleFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorCreateQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorCreateQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorCreateQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorCreateQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorCreateQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JButton createQuizButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> lessonComboBox;
    private javax.swing.JTextField quizTitleField;
    // End of variables declaration//GEN-END:variables
}
